collections:
  - name: modules
    label: BNurs Curriculum Map

    files:
      - name: year1
        label: Year 1 Modules
        file: data/year1.yml

        fields:
          - name: module_name
            label: Module Name
            type: text
